---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostvol1
spec:
  storageClassName: "fast-and-furious"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/vol1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostvol2
spec:
  storageClassName: "fast-and-furious"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/vol2"
